#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'XLForm' do

pod 'XLForm', :path => '../../'

#Following pods are used for custom row examples
pod 'AFNetworking', '~> 2.0', :inhibit_warnings => true
#pod 'XLData', :git => 'https://github.com/xmartlabs/XLData.git', :commit => '1f9019b56242a2019c7f7e11ec4ef823c397ebcf', :inhibit_warnings => true
pod 'XLData'
pod 'JVFloatLabeledTextField'
pod 'AXRatingView'
pod 'SHSPhoneComponent'
end
